name: Lint and Prettier Frontend
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  lint-and-prettier-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm i
        working-directory: frontend
      - name: ESLint
        run: npm run lint-fix
        working-directory: frontend
      - name: Prettier
        run: npm run prettier-fix
        working-directory: frontend
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Linted and Formatted code" || echo "No changes to commit"
          git pull --rebase origin ${{ github.head_ref }}
          git push origin HEAD:${{ github.head_ref }} || echo "No changes to push"
        working-directory: frontend